# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 01:33
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('publish_datetime', models.DateTimeField(default=datetime.datetime(2016, 2, 6, 9, 33, 8, 126248), verbose_name='发布时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_allowed_comment', models.BooleanField(default=True, verbose_name='是否允许评论')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容')),
                ('summary', models.TextField(blank=True, max_length=50, verbose_name='总结摘要')),
            ],
            options={
                'verbose_name': '文章',
                'ordering': ['-publish_datetime', '-id'],
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类名称')),
                ('index', models.SmallIntegerField(default=99, verbose_name='分类的序号')),
            ],
            options={
                'verbose_name': '文章类别',
                'ordering': ['index', 'id'],
                'verbose_name_plural': '文章类别',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='邮箱地址')),
                ('blog_url', models.URLField(blank=True, max_length=100, verbose_name='个人博客地址')),
                ('comment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment', models.TextField(max_length=300, verbose_name='评论内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱地址')),
                ('contact_datetime', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^((\\d{3,4}-)?\\d{7,8})$|(1[3-9][0-9]{9})$')], verbose_name='联系电话')),
                ('qq_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^([1-9][0-9]{4,10})$')], verbose_name='QQ号')),
                ('message', models.TextField(max_length=500, verbose_name='留言内容')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签'),
        ),
    ]
