# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 7, 20, 55, 45, 470526), verbose_name='发布时间'),
        ),
    ]
