# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 05:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160207_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 9, 13, 21, 37, 671986), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=80, verbose_name='总结摘要'),
        ),
    ]
