# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 16, 39, 5, 477351), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=100, verbose_name='总结摘要'),
        ),
    ]
