# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 09:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160210_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 17, 6, 57, 951274), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=140, verbose_name='总结摘要'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=800, verbose_name='留言内容'),
        ),
    ]
