# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160210_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 10, 22, 43, 2, 931721), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=100, verbose_name='总结摘要'),
        ),
    ]
